attribute "health" {
  description = "The character's health points."
  min = 0
  max = 200
  visible = true
}

attribute "strength" {
  description = "The character's physical strength."
  min = 0
  max = 100
  visible = true
}

attribute "intelligence" {
  description = "The character's mental ability."
  min = 0
  max = 100
  visible = true
}

attribute "charisma" {
  description = "The character's charisma and persuasiveness."
  min = 0
  max = 100
  visible = true
}

attribute "heller" {
  description = "The old currency of Schwäbisch Hall."
  visible = true
  min = 0
}

attribute "price" {
  description = "A price for an item to buy/sell at a retailer."
  visible = true
  min = 0
}