item "salt pan" {
  description = ""
  attributes {
    price = 125
  }
}
item "city wall fragment" {
  description = ""
}
item "night watchman lantern" {
  description = ""
}
item "ticket" {
  description = "A ticket to watch the Freilichtspiele"
}
item "costume" {
  description = ""
}

// general items
item "lockpick" {
  description = "Can be used to open doors without having a key."
  // on_interaction {
  //   add_note {
  //     title = "Usage"
  //     text = "Use 'use lockpick on <door>' to pick a lock."
  //   }
  //   hello {
  //     x = "yippie custom function"
  //   }
  //   interaction {
  //     result = NoChange
  //     description = ""
  //   }
  // }
}
item "key" {
  description = "Can be used to open doors."
}
item "clock" {
  description = "Reveals the time and epoche"
  visible = false
  commands = [
    "clock.show"
  ]
}